### ISSUE TITLE
Rozepsání integrace kalendáře v readme.md

### ISSUE THREAD

**Issue by karri84** [pirati-web/jekyll-theme-pirati#12]
Prosím o detailnější rozepsání integrace kalendáře v readme.md (example. pirati.cz)
1) Co se má v které položce změnit
2) Kde to vezmu (například u cizího kalendáře)

**Comment by xaralis** [comment]
Zdokumentováno zde: https://github.com/pirati-web/example.pirati.cz#kalednář

Pokud ke kalendáři nemáš přístup, bude ti muset pomoct někdo, kdo ten přístup má, nebo ti ten kalendář nasdílet.
