### ISSUE TITLE
Zobrazení názvu kandidátky

### ISSUE THREAD

**Issue by karri84** [pirati-web/jekyll-theme-pirati#16]
Pro případy, že web obsahuje více kandidátek s různými názvy (ne jen třeba Piráti) by bylo skvělé, kdyby se název kandidátní listiny (třeba obsažený v title) zobrazoval za textem "KANDIDÁTNÍ LISTINA" + "-" + title.

**Comment by jitka** [comment]
Omlouvám se za superpozdní odpvěď. Nejsnažší spůsob jak to zařídit je skopírovat do vašeho gitu soubor `_layouts/communal-elections.html` a v tom nadpis ručně opravit. Stejně tak můžou být měněny jakékoliv šablony. 
(Neboj se mi napsat, když budeš potřebovat něco rychleji než za půl roku.)
