### ISSUE TITLE
FB bar - nastavení názvu města

### ISSUE THREAD

**Issue by corwin78** [pirati-web/jekyll-theme-pirati#17]
Zdar, popisek FB baru se nachází přímo v theme, takže není možné jej uživatelsky změnit z _config.yml, jak by se asi očekávalo.

**Comment by michaelavodova** [comment]
Ahoj, diky! no a co s tím? Je nesmysl mít na krajských stránkách fb celé
strany.

Dne so 11. 8. 2018 10:36 uživatel Michal Breškovec <notifications@github.com>
napsal:

**Comment by corwin78** [comment]
Odkaz na FB se nastavuje normálně _config.yml, v theme je jen ten text, který by se měl nahradit proměnou a text samotný nastavovat také v rámci _config.yml - počítám, že změna by neměla být příliš náročná.

**Comment by xaralis** [comment]
@corwin78 Rozumím tomu dobře, že jde o to změnit "Facebook" třeba na "Facebook Česká Třebová"?

**Comment by xaralis** [comment]
Nově se zobrazuje FB titulek podle názvu organizace. Pokud chcete úplně speciální popisek fb skupiny, lze v `_config.yml` nastavit `facebook.profilePageName` a použije se tohle.
