### ISSUE TITLE
Mít v titulku (hlavičce) webu viditelný název místní organizace

### ISSUE THREAD

**Issue by janadamec1** [pirati-web/jekyll-theme-pirati#20]
Jde o to, že jen s pirátským logem může uživatel nabýt dojmu, že se dívá na celostátní web. Pokud není místo, tak třeba místo slov "Pirátská strana" vedle loga by trochu místa bylo. Jen je problém s delšími názvy obcí (např. Brandýs nad Labem - Stará Boleslav)

**Comment by jcz1** [comment]
Pridavam se se Stredoceskym krajem.

**Comment by jcz1** [comment]
Jako docasny hack jsme dali text/link "STREDOCESKY PIRATI" do horniho menu, ale:

Podle mě současná varianta textu/linku (ať už v textu bude cokoliv) v horním menu problém řeší jen částečně. Nepomáhá tomu ani fakt, že horní menu je určené pro odkazy na jiné weby a kód generuje odkaz, který se otevírá v novém tabu. Řešením není ani vyrobení vlastního homepage banneru, protože ten se zobrazuje jen na úvodní stránce. Nejlepší a nejjednoznačnější by IMHO bylo nahrazení textu v pirátském logu, které na první pohled upoutává pozornost a zároveň je odkazem na úvodní stránku v rámci webu.

Dalsi diskuze: https://forum.pirati.cz/viewtopic.php?f=276&p=578272

**Comment by xaralis** [comment]
![image](https://user-images.githubusercontent.com/441739/44615828-b2bff580-a843-11e8-92a0-da54d3e9ea97.png)

Fixnuto v faf7785.

**Comment by janadamec1** [comment]
Super. A co to udelat bilou barvou? Ono je to totiz fakt dulezite...

**Comment by xaralis** [comment]
@janadamec1 Dá se, si udělej PR, jestli to chceš.

**Comment by janadamec1** [comment]
OK, udelal jsem pull request: https://github.com/pirati-web/jekyll-theme-pirati/pull/35

**Comment by xaralis** [comment]
Mergnuto.
