### ISSUE TITLE
more sofisticated homepage

### ISSUE THREAD

**Issue by jitka** [pirati-web/jekyll-theme-pirati#25]
It would by nice to have includes and sass to support sofisticated homepage, even on mobile devices.

It will be used on:
https://praha.pirati.cz/
https://www.pirati.cz/

**Comment by xaralis** [comment]
This totally depends on whether it's something that has a common shape. If all these extra homepages differ too much, it would be much better to build it from ground up for each site.

Too much generalization usually leads to integration/update issues. Aim for this theme shall not be to cover all use cases, just the most frequent ones.

**Comment by jitka** [comment]
Closing since praha.pirati.cz do not use it any more and pirati.cz will have refactor which include this issue.
