### ISSUE TITLE
Lists 1st line break at wrong index in Safari (macOS, iOS)

### ISSUE THREAD

**Issue by janadamec1** [pirati-web/jekyll-theme-pirati#34]
Article lists, people lists, all break at wrong index in the 1st line on Safari (macOS, iOS)

When there are 2 columns, 1st line has 1 item, others 2.
When there are 3 columns, 1st line has 2 item, others 3.

For example, [praha.pirati.cz/lide](https://praha.pirati.cz/lide/) looks as
![pirati_list_safari](https://user-images.githubusercontent.com/32912399/47658821-f4e31b80-db93-11e8-8af3-b35113975a61.png)

Related:
Why is the default article pagination set to 11? Is it because of this issue?

**Comment by xaralis** [comment]
Please add more context: which versions?

Default pagination was set to 11 historically and should be changed to 12 AFAIK.

**Comment by janadamec1** [comment]
Any Safari version. Tested on macOS and iPad.
It worked well with old pre-pardubice theme...

**Comment by jitka** [comment]
@janadamec1  can you stil reproduce it?

**Comment by janadamec1** [comment]
Yes

**Comment by janadamec1** [comment]
Fixed in theme version 8.x
