### ISSUE TITLE
Ořezávání profilových obrázků do kruhu není úplně do kruhu

### ISSUE THREAD

**Issue by janadamec1** [pirati-web/jekyll-theme-pirati#50]
V generovaném seznamu členů nejsou bílá kolečka úplně kolečka, ale spíš vajíčka. Viz např https://praha12.pirati.cz/lide/

Na P12 máme theme 7.7.1, zdá se, že na starších verzích theme se to osekávalo dobře.

**Comment by Biluj** [comment]
Ve classe .page-content img padding-bottom zmente na nulu neb ne použivat style pro element

**Comment by janadamec1** [comment]
Díky. Nakonec jsem zjistil, že chyba byla v css pocházejícím ze šablony na plnění programu, jikoli v theme. Omlouvám se.
